### ISSUE TITLE
Fertigkeitserwerb

### ISSUE THREAD

**Issue by Tobias453** [The-Bow-Hunter/Aborea-Bot#3]
**Command**
Charaktererstellung 

**Original**
Du hast noch 8 die du Einsetzen kannst um Fertigkeiten zu erwerben

**Korrektur**
Du hast noch 8 Ausbildungspunkte die du einsetzen kannst um Fertigkeiten zu erwerben

**Comment by The-Bow-Hunter** [comment]
Im Code geändert, wird sobald ich das nächste mal den Bot update gefixed
